config/routes.rb
Rails.application.routes.draw do

  root 'posts#week_index'
  get 'week'  => 'posts#week_index'
  get 'month'  => 'posts#month_index'
  get 'year'  => 'posts#year_index'
  get 'posts/week/:week/:year'  =>  'posts#week'
  get 'posts/month/:month/:year'  =>  'posts#month'
  get 'posts/year/:year'  =>  'posts#year'

  resources :posts do
    collection do
      get :update_all
      get :week
      get :month
      get :year
    end
  end
  

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  guide            :string(255)
#  name             :string(255)
#  url              :string(255)
#  published_at     :datetime
#  week             :integer
#  month            :integer
#  year             :integer
#  image            :text
#  background_image :text
#  content          :text
#  created_at       :datetime
#  updated_at       :datetime
#

class Post < ActiveRecord::Base
    attr_accessible :guide, :name, :url, :published_at, :week, :month, :year, :image, :background_image, :content

    FlickRaw.api_key="8e60dd79e0047a5c41f6f640cf5016e8"
    FlickRaw.shared_secret="8096d39dd9f30227"
    flickr_id = '94345087@N05'
    @@flickr_feed = flickr.photos.search(:user_id => flickr_id, :sort => 'interestingness-desc')

    def self.update_from_feed
        isw_url = 'http://iswiraq.blogspot.com/feeds/posts/default?start-index=1&max-results=5000'
        urls = [isw_url]
        feeds = Feedjira::Feed.fetch_and_parse urls
        isw_feed = feeds['http://iswiraq.blogspot.com/feeds/posts/default?start-index=1&max-results=5000']

        isw_feed.entries.each_with_index do |entry, i|
            if entry.title.include? 'Situation Report'
                photo_id = @@flickr_feed[i].id
                photo_info = flickr.photos.getInfo(:photo_id => photo_id)

                record = Post.find_or_initialize_by(guide: entry.id)
                record.name             = entry.title
                record.url              = entry.url
                record.published_at     = entry.published
                record.week             = entry.published.strftime('%W')
                record.month            = entry.published.strftime('%m')
                record.year             = entry.published.strftime('%Y')
                record.guide            = entry.id
                record.image            = Nokogiri::HTML(entry.content).css('img').map{ |i| i['src'] }[0]
                record.background_image = FlickRaw.url(photo_info)
                record.content          = entry.content
                record.save
            end
        end
    end

    def self.home_background

        home_photo_id = @@flickr_feed[1].id
        home_photo_info = flickr.photos.getInfo(:photo_id => home_photo_id)
        return FlickRaw.url(home_photo_info)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def week_index
    @increment = 'week'
    @posts = Post.order("published_at DESC")
    get_range
    @increment_end = @posts.first.week
    @increment_start = @posts.last.week
    
    render "posts/index"
  end

  def month_index
    @increment = 'month'
    @posts = Post.order("published_at DESC")
    get_range
    @increment_end = @posts.first.month
    @increment_start = @posts.last.month

    render "posts/index"
  end

  def year_index
    @increment = 'year'
    @posts = Post.order("published_at DESC")
    get_range
    @increment_end = @current_year
    @increment_start = @first_year

    render "posts/index"
  end

  def week
    @increment = 'week'
    @week = params[:week]
    @year = params[:year]
    @posts = Post.order("published_at DESC").where(week: @week, year: @year)
    get_range
    render "posts/show"
  end

  def month
    @increment = 'month'
    @month = params[:month]
    @year = params[:year]
    @posts = Post.order("published_at DESC").where(month: @month, year: @year)
    get_range
    render "posts/show"
  end

  def year
    @increment = 'year'
    @year = params[:year]
    @posts = Post.order("published_at DESC").where( year: @year)
    get_range
    render "posts/show"
  end

  def update_all
    Post.update_from_feed
    flash[:notice] = "Feed Updated"
    redirect_to root_path
  end

  private
  def get_range
    @current_year = @posts.first.year
    @first_year = @posts.last.year
    @most_recent = Post.order("published_at DESC").first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'current' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_weeks_posts week, year
    return @posts = Post.order("published_at DESC").where(week: week, year: year)
  end

  def get_months_posts month, year
    return @posts = Post.order("published_at DESC").where(month: month, year: year)
  end

  def get_years_posts year
    return @posts = Post.order("published_at DESC").where(year: year)
  end

  def get_home_image
    return Post.home_background
  end
end

app/views/layouts/_footer.html.erb
<footer class="main">
  <div>
    <ul class="contributions">
      <li>Data and graphics by <a href="http://iswiraq.blogspot.com/">Institute for the Study of War Iraq</a>.</li>
      <li>Photos courtesy <a href="https://www.flickr.com/photos/leoheart/">Hussain Isa Alderazi</a>.</li>
      <li>Designed and developed by <a href="http://slightlytyler.com">slightlytyler</a>.</li>
    </ul>
  </div> 
  <section class="logo slightly">
    <i class="icomoon-logo"></i>
  </section>
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="main">
  <div class="wrapper">
    <%= link_to((image_tag 'ISW-Logo@2x.png'), root_path, class: 'home') %></a>
    <ul class="menu">
      <li><%= nav_link('Week', week_path) %></li>
      <li><%= nav_link('Month', month_path) %></li>
      <li><%= nav_link('Year', year_path) %></li>
      <li><%=link_to "Update Feed",update_all_posts_path%></li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', "http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= content_for :head %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width = device-width,initial-scale = 1.0,maximum-scale = 1.0" />
</head>
<body onload="resizeContent()" onresize="resizeContent()">

<%=render :partial=>"/layouts/header"%>
  <div id="content">
    <%= yield %>
  </div>
<%=render :partial=>"/layouts/footer"%>

</body>
</html>

app/views/posts/_list.html.erb
<% year = locals[:year] %>
<% increment_start = locals[:increment_start] %>
<% increment_end = locals[:increment_end] %>
<% (increment_start..increment_end).reverse_each do |increment| %>

  <% if @increment == 'week' %>
    <% group_posts = get_weeks_posts(increment, year) %>
    <% path = week_posts_path(:week => increment, :year => year) %>
  <% end %>

  <% if @increment == 'month' %>
    <% group_posts = get_months_posts(increment, year) %>
    <% path = month_posts_path(:month => increment, :year => year) %>
  <% end %>

  <li>
    <%= link_to(path) do %>
      <section class="background-image" style="background-image: url('<%= group_posts.first.background_image %>')"></section>
      <section class="date-info">
        <% if group_posts.last.published_at.strftime('%B') == group_posts.first.published_at.strftime('%B') %>
          <h3 class="month"><%= group_posts.last.published_at.strftime('%B') %></h3>
        <% else %>
          <h3 class="month"><%= group_posts.last.published_at.strftime('%B') %> / <%= group_posts.first.published_at.strftime('%B') %></h3>
        <% end %>
        <h4 class="week"><%= group_posts.last.published_at.strftime('%e') %> - <%= group_posts.first.published_at.strftime('%e') %></h4>
      </section>
    <% end %>
  </li>
<% end %>

app/views/posts/index.html.erb
<%=content_for :head do %>
  <style type="text/css" media="screen">
    body:before{ background-image: url('<%= get_home_image %>'); }
  </style>
<% end %>

<div class="title-container">
  <h1 class="title"><%= @increment %>s</h1>
</div>

<div class="post-list">
  <% (@first_year..@current_year).reverse_each do |year| %>

    <section class="year-banner">
      <div>
        <%= fa_icon "bookmark" %>
        <span><%= year %></span>
      </div>
    </section>

    
    <ul>
      <% if (@increment == 'year') %>
      <% group_posts = get_years_posts( year) %>
      <% path = year_posts_path(:year => year) %>

      <% (@increment_start..@increment_end).reverse_each do |increment| %>
        <li>
          <%= link_to(path) do %>
            <section class="background-image" style="background-image: url('<%= group_posts.first.background_image %>')"></section>
            <section class="date-info">
              <h3 class="increment"><%= group_posts.last.published_at.strftime('%B') %> - <%= group_posts.first.published_at.strftime('%B') %></h3>
              <h4 class="increment"><%= year %></h4>
            </section>
          <% end %>
        </li>
      <% end %>

      <% else %>
        <% (@increment_start..@increment_end).reverse_each do |increment| %>

          <% if @increment == 'week' %>
            <% group_posts = get_weeks_posts(increment, year) %>
            <% path = week_posts_path(:week => increment, :year => year) %>
          <% end %>

          <% if @increment == 'month' %>
            <% group_posts = get_months_posts(increment, year) %>
            <% path = month_posts_path(:month => increment, :year => year) %>
          <% end %>

          <li>
            <%= link_to(path) do %>
              <section class="background-image" style="background-image: url('<%= group_posts.first.background_image %>')"></section>
              <section class="date-info">
                <% if group_posts.last.published_at.strftime('%B') == group_posts.first.published_at.strftime('%B') %>
                  <h3 class="increment"><%= group_posts.last.published_at.strftime('%B') %></h3>
                <% else %>
                  <h3 class="increment"><%= group_posts.last.published_at.strftime('%B') %> / <%= group_posts.first.published_at.strftime('%B') %></h3>
                <% end %>
                <h4 class="increment"><%= group_posts.last.published_at.strftime('%e') %> - <%= group_posts.first.published_at.strftime('%e') %></h4>
              </section>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
    

  <% end %>
</div>

app/views/posts/show.html.erb
<%=content_for :head do %>
  <style type="text/css" media="screen">
    body:before{ background-image: url('<%= @posts.first.background_image %>'); }
  </style>
<% end %>

<div class="giffy-container">
  <% first = @posts.last.published_at %>
  <% last = @posts.first.published_at %>

  <% week = @posts.first.week %>
  <% month = @posts.first.month %>
  <% year = @first_year %>

  <% next_week = (!(week == 53) ? week + 1 : 01 ) %>
  <% next_month = (!(month == 12) ? month + 1 : 01 ) %>
  <% next_year = (!(week == 53) ? year : year + 1 ) %>

  <% months = (first.strftime('%B') == last.strftime('%B')) ? first.strftime('%B') : first.strftime('%B') + ' / ' + last.strftime('%B') %>

  <h2 class="title"><%= months %><br>
  <%= first.strftime('%e') %> - <%= last.strftime('%e') %></h2>

  <section class="year-banner">
    <div>
      <%= fa_icon "bookmark" %>
      <span><%= year %></span>
    </div>
  </section>

  <% @posts.reverse.each do |post| %>
    <div>
      <% if @increment == 'week' %>
        <% path = week_posts_path(:week => next_week, :year => next_year) %>
      <% elsif @increment == 'month' %>
        <% path = month_posts_path(:month => next_month, :year => next_year) %>
      <% else %>
        <% path = year_posts_path(:year => next_year) %>
      <% end %>
      <% has_next = (!(@most_recent.id == @posts.first.id) ? path : '#') %>

      <%= link_to(has_next) do %>
        <%= image_tag post.image %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/posts/week.html.erb
<%=content_for :head do %>
  <style type="text/css" media="screen">
    body{ background-image: url('<%= @posts.first.background_image %>'); }
  </style>
<% end %>

<div class="giffy-container">
  <% @posts.reverse.each do |post| %>
    <div>
      <%= image_tag post.image %>
    </div>
  <% end %>
</div>